import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#071A25', overflow: 'hidden' },
  scrollContent: { flexGrow: 1, paddingHorizontal: 24, paddingBottom: 28, maxWidth: 1280, width: '100%', alignSelf: 'center' },
  glowTop: { position: 'absolute', width: 420, height: 420, borderRadius: 210, backgroundColor: '#123E49', opacity: 0.42, top: -260, right: -170 },
  glowBottom: { position: 'absolute', width: 360, height: 360, borderRadius: 180, backgroundColor: '#0B5C52', opacity: 0.18, bottom: -230, left: -180 },
  topBar: { minHeight: 72, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: '#1D3540' },
  wordmark: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  logoMark: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: '#7EF0D2' },
  wordmarkText: { color: '#F4F8F6', fontWeight: '800', fontSize: 15, letterSpacing: 1.8 },
  systemPill: { minHeight: 36, flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 12, borderRadius: 18, borderWidth: 1, borderColor: '#2A4651', backgroundColor: 'rgba(14, 39, 50, 0.88)' },
  liveDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#7EF0D2' },
  systemPillText: { color: '#AFC0C6', fontSize: 10, fontWeight: '800', letterSpacing: 1.1 },
  hero: { flex: 1, paddingVertical: 42, gap: 40 },
  heroStacked: { flexDirection: 'column' },
  heroWide: { flexDirection: 'row', alignItems: 'center', paddingVertical: 64, minHeight: 610 },
  copyColumn: { flex: 1 },
  copyColumnWide: { paddingRight: 52 },
  eyebrow: { color: '#7EF0D2', fontSize: 11, fontWeight: '800', letterSpacing: 2.2, marginBottom: 20 },
  heroTitle: { color: '#F4F8F6', fontSize: 46, lineHeight: 52, fontWeight: '900', letterSpacing: -1.8 },
  heroTitleWide: { fontSize: 70, lineHeight: 76, letterSpacing: -3.4 },
  heroTitleAccent: { color: '#7EF0D2' },
  heroBody: { color: '#AFC0C6', fontSize: 16, lineHeight: 27, maxWidth: 560, marginTop: 24 },
  actionRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 22, marginTop: 32 },
  primaryButton: { minHeight: 56, flexDirection: 'row', alignItems: 'center', gap: 18, paddingLeft: 22, paddingRight: 8, borderRadius: 28, backgroundColor: '#7EF0D2' },
  buttonPressed: { opacity: 0.78 },
  primaryButtonText: { color: '#071A25', fontSize: 16, fontWeight: '800' },
  primaryButtonIcon: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F4F8F6' },
  versionBlock: { paddingLeft: 18, borderLeftWidth: 1, borderLeftColor: '#2A4651' },
  versionLabel: { color: '#6F8792', fontSize: 9, fontWeight: '800', letterSpacing: 1.6 },
  versionValue: { color: '#D5E1E2', fontSize: 12, fontWeight: '700', marginTop: 4 },
  visualColumn: { flex: 1, minHeight: 380 },
  visualColumnWide: { minHeight: 520 },
  imageFrame: { flex: 1, minHeight: 380, borderRadius: 36, overflow: 'hidden', backgroundColor: '#102D38', borderWidth: 1, borderColor: '#2A4651' },
  hardwareImage: { width: '100%', height: '100%', position: 'absolute' },
  imageShade: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(3, 20, 28, 0.34)' },
  signalBadge: { position: 'absolute', left: 18, right: 18, bottom: 18, flexDirection: 'row', alignItems: 'center', gap: 12, padding: 14, borderRadius: 20, backgroundColor: 'rgba(7, 26, 37, 0.9)', borderWidth: 1, borderColor: '#36515B' },
  signalIcon: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: '#153942' },
  signalLabel: { color: '#7EF0D2', fontSize: 9, fontWeight: '800', letterSpacing: 1.8 },
  signalValue: { color: '#F4F8F6', fontSize: 14, fontWeight: '700', marginTop: 3 },
  orbitLabel: { position: 'absolute', top: 20, right: 20, alignItems: 'flex-end' },
  orbitIndex: { color: '#7EF0D2', fontSize: 38, fontWeight: '200' },
  orbitText: { color: '#D5E1E2', textAlign: 'right', fontSize: 9, fontWeight: '800', letterSpacing: 1.4, lineHeight: 14 },
  metricsStrip: { flexDirection: 'row', borderTopWidth: 1, borderBottomWidth: 1, borderColor: '#1D3540', paddingVertical: 22 },
  metric: { flex: 1, paddingHorizontal: 12 },
  metricBorder: { borderLeftWidth: 1, borderLeftColor: '#1D3540' },
  metricValue: { color: '#F4F8F6', fontSize: 22, fontWeight: '800', fontVariant: ['tabular-nums'] },
  metricUnit: { color: '#7EF0D2', fontSize: 11, fontWeight: '800' },
  metricLabel: { color: '#6F8792', fontSize: 10, lineHeight: 15, marginTop: 5 },
  footerLine: { minHeight: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  footerText: { color: '#6F8792', fontSize: 9, fontWeight: '800', letterSpacing: 1.7 },
});
